# Generated by Django 3.0.8 on 2020-09-01 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('orderDetailId', models.AutoField(primary_key=True, serialize=False)),
                ('orderAmount', models.CharField(default=0, max_length=100)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('orderShipAdd', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=10)),
                ('paymentMethod', models.CharField(default='Credit Card', max_length=10)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
