# Generated by Django 3.0.8 on 2020-09-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderDetail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='orderAmount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='paymentMethod',
            field=models.CharField(default='CreditCard', max_length=20),
        ),
    ]
