# Generated by Django 3.0.8 on 2020-08-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('productDesc', models.CharField(max_length=200)),
                ('productStock', models.CharField(default=0, max_length=10)),
                ('productPrice', models.CharField(default=0, max_length=10)),
                ('productImage', models.ImageField(upload_to='')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
