# Generated by Django 3.0.8 on 2020-08-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('userAge', models.CharField(max_length=10)),
                ('userMaxPurchase', models.CharField(max_length=1000)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('totalOrderPlaced', models.CharField(default=0, max_length=10)),
                ('userPhone', models.CharField(max_length=10)),
                ('usermailId', models.CharField(max_length=100)),
                ('userPassword', models.CharField(max_length=20)),
                ('userAddress', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=10)),
            ],
        ),
    ]
