# Generated by Django 3.0.8 on 2020-10-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_creditcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='creditCard',
            new_name='creditCard_1',
        ),
        migrations.AddField(
            model_name='user',
            name='creditCard_2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='creditCard_3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='creditCard_4',
            field=models.CharField(default='', max_length=20),
        ),
    ]
